### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by sergeiandreyev** [FatsieFS/Salt-C4M_PDK_IHPSG13G2#1]
Installed the package for KLayout 0.29.1, having the following `ImportError`:
ERROR: /home/andreev/opensource/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout/salt/C4M/FlexLibs/python/c4m/flexcell/factory.py:9: ImportError: cannot import name 'CoriolisExportSpec' from 'pdkmaster.io.coriolis' (/usr/local/lib/python3.10/dist-packages/pdkmaster/io/coriolis/__init__.py)
  /home/andreev/opensource/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout/salt/C4M/FlexLibs/python/c4m/flexcell/factory.py:9
  /home/andreev/opensource/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout/salt/C4M/FlexLibs/python/c4m/flexcell/__init__.py:3
  /home/andreev/opensource/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout/salt/C4M/PDK/IHPSG13G2/python/c4m/pdk/ihpsg13g2/__init__.py:7
  /home/andreev/opensource/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout/salt/C4M/PDK/IHPSG13G2/pymacros/RegisterPrimLib.lym:2 (class ImportError)

Could you please take a look?

**Comment by FatsieFS** [comment]
1. Do you have `~/.klayout` linked to `/home/andreev/opensource/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout` ?
I find it strange that the salt package seems to be installed in `/home/andreev/opensource/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout/salt/` and not `~/.klayout/salt`.
2. There seems to an outdated pdkmaster version in your local `/usr/local/lib/python3.10/dist-packages/` path as he should have the right version in `/home/andreev/opensource/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout/salt/PDKMaster/python`

**Comment by sergeiandreyev** [comment]
Hi @FatsieFS, please find my comments below:
1. I'm running KLayout w/ `KLAYOUT_HOME` env variable pointing to the location of PDK specific tool data, which in our case is stored in  `.../libs.tech/klayout` folder in our GitHub repo
2. I uninstalled PDKMaster 0.9.0 and now can confirm that there are no more issues - cells are instantiated correctly

**Comment by FatsieFS** [comment]
Thanks, closing this issue.
